// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_DB_URL = import.meta.env.VITE_SUPABASE_DB_URL as string | undefined;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

export const SUPABASE_AVAILABLE = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_AVAILABLE) {
  console.error('Supabase environment variables are missing. The app will run without backend connectivity.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a client even if credentials are missing so the rest of the code can run
const placeholderUrl = 'http://localhost';
const placeholderKey = 'public-anon-key';

export const supabase: SupabaseClient<Database> = createClient(
  SUPABASE_URL || placeholderUrl,
  SUPABASE_PUBLISHABLE_KEY || placeholderKey
);

